name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make environment setup script executable
      shell: bash
      run: chmod +x ./environmentSetup.sh ${{ secrets.Artifactory_username }} ${{ secrets.Artifactory_password }}
    - name: Set up environment
      shell: bash
      run: ./environmentSetup.sh
    - name: Make gradlew executable
      shell: bash
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew :rxverid:test
